-- V13: Migration placeholder for future prescription test data
-- Note: Sample prescription data has been removed to avoid foreign key constraint violations
-- The prescriptions feature is fully functional - doctors can create prescriptions through the application
-- If test data is needed in future, use SELECT subqueries to reference existing patient/doctor IDs instead of hardcoded values
